### PR TITLE
rasdaemon: mix fixes

### PR DESCRIPTION
**Pull request by aristeu**
These patches are for 3 issues found with covscan. None of them are likely to
happen during regular use, but worth fixing anyway.

### CODE REVIEW

**Comment by aristeu** [comment]
Mauro?

**Review by shijujose4 — COMMENTED** [review]
Hi Aristeu,

This fix need may be required for all other events as well because this part of the code is same for all the events.

Thanks,
Shiju

**Comment by aristeu** [comment]
> This fix need may be required for all other events as well because this part of the code is same for all the events.

Updated. Thanks!

**Comment by shijujose4** [comment]
Thanks.

**Comment by mchehab** [comment]
applied, thanks!

**Pull request closed without merging**
